---
- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"
    register: tomcat_download

- name: Create the tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    register: tomcat_directory

- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /opt/tomcat/versions
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /
    when: tomcat_directory

- name: Copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"