---
- name: Install chrony on Ubuntu
  ansible.builtin.apt:
    name: chrony
    state: present
  when: os_distribution == 'Ubuntu'

- name: Install chrony on Debian
  ansible.builtin.apt:
    name: chrony
    state: present
  when: os_distribution == 'Debian'

- name: Install chrony on CentOS/RHEL
  ansible.builtin.yum:
    name: chrony
    state: present
  when: os_distribution == 'CentOS' or os_distribution == 'RedHat'
