---
- name: Check OS Distribution
  ansible.builtin.set_fact:
    os_distribution: "{{ ansible_distribution }}"
    os_version: "{{ ansible_distribution_major_version }}"

- name: Install wget on Ubuntu
  ansible.builtin.apt:
    name: wget
    state: present
  when: os_distribution == 'Ubuntu'

- name: Install wget on Debian
  ansible.builtin.apt:
    name: wget
    state: present
  when: os_distribution == 'Debian'

- name: Install wget on CentOS/RHEL
  ansible.builtin.yum:
    name: wget
    state: present
  when: os_distribution == 'CentOS' or os_distribution == 'RedHat'

