---
- name: Check OS Distribution
  ansible.builtin.set_fact:
    os_distribution: "{{ ansible_distribution }}"
    os_version: "{{ ansible_distribution_major_version }}"

- name: Get System Memory
  ansible.builtin.command: "free -b | grep '^Mem:' | awk '{print $2}'"
  register: system_memory_raw
  changed_when: false
  ignore_errors: true

- name: Calculate Swap Size
  ansible.builtin.set_fact:
    swap_size: "{{ (system_memory_raw.stdout | int * 1.5) | int | round(0, 'ceil') }}"
  when: system_memory_raw.stdout is defined

- name: Configure Swap File
  ansible.builtin.when: swap_size > 0
  ansible.builtin.copy:
    dest: /swapfile
    content: ""
    owner: root
    group: root
    mode: '0600'
    backup: yes

- name: Set Swap File Size
  ansible.builtin.command: "dd if=/dev/zero of=/swapfile bs=1M count={{ swap_size }}"
  ansible.builtin.when: swap_size > 0

- name: Set Swap File Permissions
  ansible.builtin.file:
    path: /swapfile
    mode: '0600'
  ansible.builtin.when: swap_size > 0

- name: Set Up Swap Space
  ansible.builtin.command: "mkswap /swapfile"
  ansible.builtin.when: swap_size > 0

- name: Enable Swap
  ansible.builtin.command: "swapon /swapfile"
  ansible.builtin.when: swap_size > 0

- name: Add Swap to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile swap swap defaults 0 0"
  ansible.builtin.when: swap_size > 0

- name: Check Swap Status
  ansible.builtin.command: "swapon --show"
  register: swap_status
  changed_when: false
  ignore_errors: true
  ansible.builtin.when: swap_size > 0

- name: Display Swap Information
  ansible.builtin.debug:
    msg: "Swap is configured: {{ swap_status.stdout }}"
  ansible.builtin.when: swap_status.rc == 0

