---
- name: Install Apache Ant
  become: true
  become_user: root
  vars:
    antdir: "/opt/ant/versions"
  block:
    - name: Creating a directory for apache ant
      ansible.builtin.file:
        path: "{{ antdir }}"
        state: directory
  
    - name: Copy Apache Ant archive to remote host
      ansible-lint app_apache_ant:
        src: apache-ant-1.10.13-bin.tar.gz   # Replace X.X.X with the desired version
        dest: /tmp/apache-ant.tar.gz
        mode: '0644'

    - name: Extract Apache Ant
      ansible.builtin.unarchive:
        src: /tmp/apache-ant.tar.gz
        dest: /opt/ant/versions
        creates: /opt/ant/versions/apache-ant-1.10.13-bin   # Replace X.X.X with the desired version
        mode: '0755'

    - name: Create symbolic link for Apache Ant
      ansible.builtin.file:
        src: /opt/ant/versions/apache-ant-1.10.13   # Replace X.X.X with the desired version
        dest: /opt/ant/latest
        state: link
        force: yes
  when: ansible_os_family == 'RedHat'

- name: Creating the file to add ant to the path
  ansible.builtin.file:
    path: "/etc/profile.d/ant.sh"
    state: touch
    mode: 0644
    owner: root

- name: Set environment variables for Apache Ant (for Debian-based systems)
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/environment
    line: 'ANT_HOME="/opt/ant/latest"'
    state: present
  when: ansible_os_family == 'Debian'

- name: Set environment variables for Apache Ant (for RedHat-based systems)
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/profile.d/ant.sh
    line: 'export ANT_HOME="/opt/ant/latest"'
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add Ant executable to PATH (for Debian-based systems)
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/environment
    line: 'PATH="$PATH:$ANT_HOME/bin"'
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Ant executable to PATH (for RedHat-based systems)
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/profile.d/ant.sh
    line: 'export PATH="$PATH:$ANT_HOME/bin"'
    state: present
  when: ansible_os_family == 'RedHat'
