---
- name: Check OS Distribution
  ansible.builtin.set_fact:
    os_distribution: "{{ ansible_distribution }}"
    os_version: "{{ ansible_distribution_major_version }}"

- name: Install bind-utils on Ubuntu
  ansible.builtin.apt:
    name: bind9-utils
    state: present
  when: os_distribution == 'Ubuntu'

- name: Install bind-utils on Debian
  ansible.builtin.apt:
    name: dnsutils
    state: present
  when: os_distribution == 'Debian'

- name: Install bind-utils on CentOS/RHEL 7
  ansible.builtin.yum:
    name: bind-utils
    state: present
  when: os_distribution == 'CentOS' and os_version == '7'

- name: Install bind-utils on CentOS/RHEL 8
  ansible.builtin.dnf:
    name: bind-utils
    state: present
  when: os_distribution == 'CentOS' and os_version == '8'

