---
- name: Check OS Distribution
  ansible.builtin.set_fact:
    os_distribution: "{{ ansible_distribution }}"
    os_version: "{{ ansible_distribution_major_version }}"

- name: Configure Static Swap File
  ansible.builtin.when: os_distribution == 'Ubuntu' and os_version == '18.04'
  ansible.builtin.command: "fallocate -l 8G /swapfile"

- name: Configure Static Swap File
  ansible.builtin.when: os_distribution == 'Debian' and os_version == '10'
  ansible.builtin.command: "fallocate -l 8G /swapfile"

- name: Configure Static Swap File
  ansible.builtin.when: os_distribution == 'CentOS' and os_version == '7'
  ansible.builtin.command: "dd if=/dev/zero of=/swapfile bs=1M count=8192"

- name: Set Swap File Permissions
  ansible.builtin.file:
    path: /swapfile
    mode: '0600'

- name: Set Up Swap Space
  ansible.builtin.command: "mkswap /swapfile"

- name: Enable Swap
  ansible.builtin.command: "swapon /swapfile"

- name: Add Swap to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile swap swap defaults 0 0"

- name: Check Swap Status
  ansible.builtin.command: "swapon --show"
  register: swap_status
  changed_when: false
  ignore_errors: true

- name: Display Swap Information
  ansible.builtin.debug:
    msg: "Swap is configured: {{ swap_status.stdout }}"
  ansible.builtin.when: swap_status.rc == 0

