---
- name: Create somename.sh file
  template:
    src: somename.sh.j2
    dest: /etc/profile.d/somename.sh
  become: true

- name: Set correct permissions
  file:
    path: /etc/profile.d/somename.sh
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Source the file for immediate effect
  shell: source /etc/profile.d/somename.sh
  args:
    executable: /bin/bash

