---
- name: Download Amazon CLI v2 installer
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: /tmp/awscliv2.zip

- name: Unzip Amazon CLI v2 installer
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/awscliv2

- name: Install Amazon CLI v2
  ansible.builtin.command: /tmp/awscliv2/aws/install
  args:
    creates: /usr/local/bin/aws

- name: Create /etc/profile.d/awscli.sh to add awscli to PATH
  ansible.builtin.template:
    src: awscli.sh.j2
    dest: /etc/profile.d/awscli.sh
    owner: root
    group: root
    mode: '0755'

