---
- name: Install package dependencies.
  package: name={{ item }} state=present
  with_items:
    - python
    - unzip

- name: Download awscliv2 installer.
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
    dest: "{{ executable_temp_dir }}"
    remote_src: true
    creates: '{{ executable_temp_dir }}/aws'
    mode: 0755

- name: Run the installer.
  command:
  args:
    cmd: "{{ executable_temp_dir }}/aws/install"
    creates: /usr/local/bin/aws
  become: true
  register: aws_install
  
- name: "Show installer output."
  debug:
    var: aws_install
    verbosity: 2

- name: Create /etc/profile.d/awscli.sh to add awscli to PATH
  ansible.builtin.template:
    src: awscli.sh.j2
    dest: /etc/profile.d/awscli.sh
    owner: root
    group: root
    mode: '0755'
