---
platforms:
  - name: instance
    image: ubuntu:18.04
    privileged: True
    command: /sbin/init
  - name: centos-7
    image: centos:7
    privileged: True
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8