---
- name: Check OS Distribution
  ansible.builtin.set_fact:
    os_distribution: "{{ ansible_distribution }}"
    os_version: "{{ ansible_distribution_major_version }}"

- name: Install unzip on Ubuntu
  ansible.builtin.apt:
    name: unzip
    state: present
  when: os_distribution == 'Ubuntu'

- name: Install unzip on Debian
  ansible.builtin.apt:
    name: unzip
    state: present
  when: os_distribution == 'Debian'

- name: Install unzip on CentOS/RHEL
  ansible.builtin.yum:
    name: unzip
    state: present
  when: os_distribution == 'CentOS' or os_distribution == 'RedHat'

