---
- name: Check OS Distribution
  ansible.builtin.set_fact:
    os_distribution: "{{ ansible_distribution }}"
    os_version: "{{ ansible_distribution_major_version }}"

- name: Install net-tools on Ubuntu
  ansible.builtin.apt:
    name: net-tools
    state: present
  when: os_distribution == 'Ubuntu'

- name: Install net-tools on Debian
  ansible.builtin.apt:
    name: net-tools
    state: present
  when: os_distribution == 'Debian'

- name: Install net-tools on CentOS/RHEL
  ansible.builtin.yum:
    name: net-tools
    state: present
  when: os_distribution == 'CentOS' or os_distribution == 'RedHat'

